#### crowsnest.conf
#### This is a typical default config.
#### Also used as default in mainsail / MainsailOS
#### See:
#### https://github.com/mainsail-crew/crowsnest/blob/master/README.md
#### for details to configure to your needs.


#####################################################################
####                                                            #####
####      Information about ports and according URL's           #####
####                                                            #####
#####################################################################
####                                                            #####
####    Port 8080 equals /webcam/?action=[stream/snapshot]      #####
####    Port 8081 equals /webcam2/?action=[stream/snapshot]     #####
####    Port 8082 equals /webcam3/?action=[stream/snapshot]     #####
####    Port 8083 equals /webcam4/?action=[stream/snapshot]     #####
####                                                            #####
#####################################################################
####    RTSP Stream URL: ( if enabled and supported )           #####
####    rtsp://<ip>:<rtsp_port>/stream.h264                     #####
#####################################################################

[crowsnest]
log_path: /home/vertigo/printer_data/logs/crowsnest.log
log_level: verbose
delete_log: false
no_proxy: false

[cam 1]
# mode: ustreamer                         # https://docs.mainsail.xyz/crowsnest/faq/backends
mode: camera-streamer                   # Use for low latency with smaller resolution below
port: 8080                              # HTTP/MJPG stream/snapshot port
device: /dev/video0                     # See log for available devices
# resolution: 2592x1944                   # <width>x<height> format
resolution: 640x480                     # use for low latency 'real time' video with streamer above
max_fps: 5                              # if hardware supports it, it will be forced, otherwise ignored/coerced.
v4l2ctl: brightness=-20,contrast=20,power_line_frequency=2     # Add v4l2-ctl parameters to set up your camera, see log for your camera capabilities.
# custom_flags: --drop-same-frames=30

