title: Vertigo Mk1 Docs
description: A collaborative effort by Vertigo Mk1 enthusiasts
theme: just-the-docs

url: https://AutomatedLayers.github.io

aux_links:
  "Automated Layers Site":
    "https://AutomatedLayers.com"
  "Vertigo Mk1 Github":
    "https://github.com/AutomatedLayers/VertigoMk1"
  "Edit These Docs :)":
    "https://github.com/AutomatedLayers/VertigoMk1/tree/main/docs"

logo: "/assets/images/VertigoMk1Docs_dark.png"

favicon_ico: "favicon.ico"

callouts:
  warning:
    title: Warning
    color: red

color_scheme: vertigo_dark

include:
  [_includes]