title: Vertigo Mk1 Docs
description: A collaborative effort by Vertigo Mk1 enthusiasts
theme: just-the-docs

url: https://AutomatedLayers.github.io
repository_url: https://github.com/AutomatedLayers/VertigoMk1/edit/main/docs

aux_links:
  "<img src='assets/images/AL_logo_icon.svg' width='16' height='16' style='vertical-align:middle;margin-right:4px'/>&nbsp;Automated Layers":
    - "https://AutomatedLayers.com"
  "<i class='fa-brands fa-github'></i>&nbsp;GitHub":
    - "https://github.com/AutomatedLayers/VertigoMk1"
  "<i class='fa-solid fa-mug-saucer'></i>&nbsp;Buy Us A Coffee":
    - "https://buymeacoffee.com/automatedlayers"
  "<i class='fa-brands fa-discord'></i>&nbsp;Discord":
    - "https://discord.gg/qCQRbnZ6"

logo: "/assets/images/VertigoMk1Docs_dark.png"

favicon_ico: "favicon.ico"

callouts:
  warning:
    title: Warning
    color: red

  important:
    title: Important
    color: yellow

  note:
    title: Note
    color: green

color_scheme: vertigo_light

default_language: en
